"""RFC 7807 Problem Details schemas for error responses."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ProblemDetail(BaseModel):
    """RFC 7807 Problem Details for HTTP APIs.

    This schema provides a standardized way to carry machine-readable
    details of errors in HTTP responses.

    References:
        https://www.rfc-editor.org/rfc/rfc7807.html

    Attributes:
        type: URI reference identifying the problem type.
        title: Short human-readable summary of the problem type.
        status: HTTP status code generated by the origin server.
        detail: Human-readable explanation specific to this occurrence.
        instance: URI reference identifying the specific occurrence.

    Example:
        ```python
        problem = ProblemDetail(
            type="https://example.com/problems/resource-not-found",
            title="Resource Not Found",
            status=404,
            detail="User with ID 'abc123' was not found in the database",
            instance="/api/v1/users/abc123",
            user_id="abc123"
        )
        ```
    """

    type: str = Field(
        default="about:blank",
        description="URI reference identifying the problem type",
        examples=["resource-not-found", "validation-error"],
    )
    title: str = Field(
        description="Short human-readable summary of the problem type",
        examples=["Not Found", "Validation Error"],
    )
    status: int = Field(
        description="HTTP status code",
        ge=100,
        le=599,
        examples=[404, 422, 500],
    )
    detail: str = Field(
        description="Human-readable explanation specific to this occurrence",
        examples=["User with ID 'abc123' was not found"],
    )
    instance: str | None = Field(
        default=None,
        description="URI reference identifying this specific occurrence",
        examples=["/api/v1/users/abc123"],
    )

    model_config = {
        "extra": "allow",  # Allow additional fields for context-specific information
        "json_schema_extra": {
            "examples": [
                {
                    "type": "validation-error",
                    "title": "Validation Error",
                    "status": 422,
                    "detail": "Email address format is invalid",
                    "instance": "/api/v1/users",
                    "field": "email",
                    "value": "invalid@",
                },
                {
                    "type": "rate-limit-exceeded",
                    "title": "Too Many Requests",
                    "status": 429,
                    "detail": "Rate limit exceeded",
                    "instance": "/api/v1/data",
                    "retry_after": 60,
                    "limit": 100,
                    "window": "minute",
                },
            ]
        },
    }

    def __init__(self, **data: Any) -> None:
        """Initialize problem detail with support for extra fields.

        Args:
            **data: Problem detail fields including standard and extension members.
        """
        super().__init__(**data)


class ValidationError(BaseModel):
    """Validation error detail for a specific field.

    Attributes:
        field: The field path that failed validation.
        message: Human-readable error message.
        type: The type of validation error.
        value: The invalid value that was provided (optional).

    Example:
        ```python
        error = ValidationError(
            field="email",
            message="Email address format is invalid",
            type="format",
            value="invalid@"
        )
        ```
    """

    field: str = Field(
        description="Field path that failed validation",
        examples=["email", "user.address.zipcode"],
    )
    message: str = Field(
        description="Human-readable error message",
        examples=["Email address format is invalid"],
    )
    type: str = Field(
        description="Type of validation error",
        examples=["format", "required", "min_length", "max_length", "pattern"],
    )
    value: Any | None = Field(
        default=None,
        description="The invalid value that was provided",
        examples=["invalid@", "", 999],
    )


class ValidationProblemDetail(ProblemDetail):
    """Extended Problem Details for validation errors with field-level information.

    Attributes:
        errors: List of field-specific validation errors.

    Example:
        ```python
        problem = ValidationProblemDetail(
            type="validation-error",
            title="Validation Error",
            status=422,
            detail="Request validation failed for 2 fields",
            instance="/api/v1/users",
            errors=[
                ValidationError(
                    field="email",
                    message="Email address format is invalid",
                    type="format",
                    value="invalid@"
                ),
                ValidationError(
                    field="age",
                    message="Must be at least 18",
                    type="min_value",
                    value=15
                ),
            ]
        )
        ```
    """

    errors: list[ValidationError] = Field(
        default_factory=list,
        description="List of field-specific validation errors",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "type": "validation-error",
                    "title": "Validation Error",
                    "status": 422,
                    "detail": "Request validation failed for 2 fields",
                    "instance": "/api/v1/users",
                    "errors": [
                        {
                            "field": "email",
                            "message": "Email address format is invalid",
                            "type": "format",
                            "value": "invalid@",
                        },
                        {
                            "field": "age",
                            "message": "Must be at least 18",
                            "type": "min_value",
                            "value": 15,
                        },
                    ],
                }
            ]
        }
    }
