"""initial_schema

Revision ID: 02aeb38ec26e
Revises:
Create Date: 2025-12-03 21:02:17.772038+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from example_service.core.database.search.utils import FTSMigrationHelper
from example_service.features.webhooks.models import StringArray
from example_service.core.database.search.types import TSVECTOR
from example_service.core.database.types import EncryptedString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02aeb38ec26e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL extensions (ltree, pg_trgm, etc.) are auto-injected
    # by alembic/inject_fts.py based on model detection

    sa.Enum("1", "2", "3", "4", name="jobpriority").create(op.get_bind())
    sa.Enum(
        "pending",
        "queued",
        "running",
        "completed",
        "failed",
        "cancelled",
        "retrying",
        "paused",
        name="jobstatus",
    ).create(op.get_bind())
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", name="aijobstatus").create(
        op.get_bind()
    )
    sa.Enum(
        "TRANSCRIPTION",
        "PII_REDACTION",
        "SUMMARY",
        "SENTIMENT",
        "COACHING",
        "FULL_ANALYSIS",
        name="aijobtype",
    ).create(op.get_bind())
    sa.Enum(
        "LLM", "TRANSCRIPTION", "EMBEDDING", "IMAGE", "PII_REDACTION", name="aiprovidertype"
    ).create(op.get_bind())
    sa.Enum("enabled", "disabled", "percentage", "targeted", name="flagstatus").create(
        op.get_bind()
    )
    sa.Enum(
        "create",
        "read",
        "update",
        "delete",
        "bulk_create",
        "bulk_update",
        "bulk_delete",
        "export",
        "import",
        "login",
        "logout",
        "login_failed",
        "password_change",
        "token_refresh",
        "permission_denied",
        "acl_check",
        "archive",
        "restore",
        "purge",
        name="auditaction",
    ).create(op.get_bind())
    sa.Enum("pending", "processing", "ready", "failed", "deleted", name="filestatus").create(
        op.get_bind()
    )
    sa.Enum("pending", "delivered", "failed", "retrying", name="deliverystatus").create(
        op.get_bind()
    )
    sa.Enum(
        "smtp", "aws_ses", "sendgrid", "mailgun", "console", "file", name="emailprovidertype"
    ).create(op.get_bind())
    op.create_table(
        "audit_logs",
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the action occurred",
        ),
        sa.Column(
            "action",
            postgresql.ENUM(
                "create",
                "read",
                "update",
                "delete",
                "bulk_create",
                "bulk_update",
                "bulk_delete",
                "export",
                "import",
                "login",
                "logout",
                "login_failed",
                "password_change",
                "token_refresh",
                "permission_denied",
                "acl_check",
                "archive",
                "restore",
                "purge",
                name="auditaction",
                create_type=False,
            ),
            nullable=False,
            comment="Type of action performed",
        ),
        sa.Column(
            "entity_type", sa.String(length=100), nullable=False, comment="Type of entity affected"
        ),
        sa.Column(
            "entity_id", sa.String(length=255), nullable=True, comment="ID of the affected entity"
        ),
        sa.Column(
            "user_id", sa.String(length=255), nullable=True, comment="User who performed the action"
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=True, comment="Tenant context"),
        sa.Column(
            "old_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Previous state (for updates/deletes)",
        ),
        sa.Column(
            "new_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="New state (for creates/updates)",
        ),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Changed fields with old/new values",
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True, comment="Client IP address"),
        sa.Column("user_agent", sa.String(length=500), nullable=True, comment="Client user agent"),
        sa.Column(
            "request_id", sa.String(length=100), nullable=True, comment="Request correlation ID"
        ),
        sa.Column("endpoint", sa.String(length=255), nullable=True, comment="API endpoint path"),
        sa.Column("method", sa.String(length=10), nullable=True, comment="HTTP method"),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional context data",
        ),
        sa.Column("success", sa.Boolean(), nullable=False, comment="Whether the action succeeded"),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error details if action failed"
        ),
        sa.Column(
            "duration_ms", sa.Integer(), nullable=True, comment="Action duration in milliseconds"
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="UUID v7 primary key (time-sortable)"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_action_entity", "audit_logs", ["action", "entity_type"], unique=False)
    op.create_index("ix_audit_entity", "audit_logs", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_index("ix_audit_tenant_time", "audit_logs", ["tenant_id", "timestamp"], unique=False)
    op.create_index("ix_audit_user_time", "audit_logs", ["user_id", "timestamp"], unique=False)
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=100), nullable=False, comment="Unique flag key"),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Human-readable name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Flag description"),
        sa.Column(
            "status",
            postgresql.ENUM(
                "enabled",
                "disabled",
                "percentage",
                "targeted",
                name="flagstatus",
                create_type=False,
            ),
            nullable=False,
            comment="Flag status",
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False, comment="Global enabled state"),
        sa.Column("percentage", sa.Integer(), nullable=False, comment="Rollout percentage (0-100)"),
        sa.Column(
            "targeting_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Targeting rules for selective rollout",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional flag metadata",
        ),
        sa.Column(
            "starts_at", sa.DateTime(timezone=True), nullable=True, comment="Activation start time"
        ),
        sa.Column(
            "ends_at", sa.DateTime(timezone=True), nullable=True, comment="Activation end time"
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="UUID v7 primary key (time-sortable)"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
    )
    op.create_index("ix_feature_flags_enabled", "feature_flags", ["enabled"], unique=False)
    op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
    op.create_index("ix_feature_flags_status", "feature_flags", ["status"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("bucket", sa.String(length=63), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "processing",
                "ready",
                "failed",
                "deleted",
                name="filestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=255),
            nullable=True,
            comment="Tenant ID for multi-tenant isolation",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
    )
    op.create_index(op.f("ix_files_owner_id"), "files", ["owner_id"], unique=False)
    op.create_index(op.f("ix_files_status"), "files", ["status"], unique=False)
    op.create_index(op.f("ix_files_storage_key"), "files", ["storage_key"], unique=True)
    op.create_index(op.f("ix_files_tenant_id"), "files", ["tenant_id"], unique=False)
    op.create_table(
        "flag_overrides",
        sa.Column("flag_key", sa.String(length=100), nullable=False, comment="Feature flag key"),
        sa.Column(
            "entity_type",
            sa.String(length=20),
            nullable=False,
            comment="Entity type (user, tenant)",
        ),
        sa.Column("entity_id", sa.String(length=100), nullable=False, comment="Entity ID"),
        sa.Column("enabled", sa.Boolean(), nullable=False, comment="Override value"),
        sa.Column("reason", sa.Text(), nullable=True, comment="Reason for override"),
        sa.Column("id", sa.Uuid(), nullable=False, comment="UUID v7 primary key (time-sortable)"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag_overrides")),
    )
    op.create_index(
        "ix_flag_overrides_entity", "flag_overrides", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_flag_overrides_flag_key"), "flag_overrides", ["flag_key"], unique=False
    )
    op.create_index(
        "ix_flag_overrides_lookup",
        "flag_overrides",
        ["flag_key", "entity_type", "entity_id"],
        unique=True,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "task_name", sa.String(length=255), nullable=False, comment="Name of the task function"
        ),
        sa.Column(
            "task_args",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Task arguments as JSON",
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                "retrying",
                "paused",
                name="jobstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("1", "2", "3", "4", name="jobpriority", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "parent_job_id",
            sa.Uuid(),
            nullable=True,
            comment="Parent job ID for workflow hierarchies",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), nullable=True, comment="When job entered queue"
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When execution started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When job completed/failed",
        ),
        sa.Column(
            "paused_at", sa.DateTime(timezone=True), nullable=True, comment="When job was paused"
        ),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=True,
            comment="Auto-cancel if running longer than this",
        ),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Delayed execution start time",
        ),
        sa.Column(
            "duration_ms", sa.Float(), nullable=True, comment="Execution duration in milliseconds"
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Total cost in USD",
        ),
        sa.Column(
            "result_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Job result data",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message if failed"),
        sa.Column(
            "retry_count", sa.Integer(), nullable=False, comment="Current retry attempt number"
        ),
        sa.Column("max_retries", sa.Integer(), nullable=False, comment="Maximum retry attempts"),
        sa.Column("cancel_reason", sa.Text(), nullable=True, comment="Reason for cancellation"),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["jobs.id"],
            name=op.f("fk_jobs_parent_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_completed_cleanup",
        "jobs",
        ["completed_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"),
    )
    op.create_index(op.f("ix_jobs_parent_job_id"), "jobs", ["parent_job_id"], unique=False)
    op.create_index(
        "ix_jobs_priority_queued",
        "jobs",
        [sa.literal_column("priority DESC"), sa.literal_column("created_at ASC")],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_jobs_running_timeout",
        "jobs",
        ["started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running' AND timeout_seconds IS NOT NULL"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_task_name"), "jobs", ["task_name"], unique=False)
    op.create_index("ix_jobs_task_name_status", "jobs", ["task_name", "status"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.create_index("ix_jobs_tenant_status", "jobs", ["tenant_id", "status"], unique=False)
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("remind_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "recurrence_rule",
            sa.String(length=255),
            nullable=True,
            comment="iCalendar RRULE string for recurring reminders",
        ),
        sa.Column(
            "recurrence_end_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the recurrence series ends",
        ),
        sa.Column(
            "parent_id",
            sa.Uuid(),
            nullable=True,
            comment="Parent reminder ID for occurrences broken out from a series",
        ),
        sa.Column(
            "occurrence_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Specific occurrence date for broken-out instances",
        ),
        sa.Column(
            "search_vector",
            TSVECTOR(),
            nullable=True,
            comment="Full-text search vector for title and description",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=255),
            nullable=True,
            comment="Tenant ID for multi-tenant isolation",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["reminders.id"],
            name=op.f("fk_reminders_parent_id_reminders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    op.create_index(op.f("ix_reminders_parent_id"), "reminders", ["parent_id"], unique=False)
    op.create_index(op.f("ix_reminders_tenant_id"), "reminders", ["tenant_id"], unique=False)
    op.create_table(
        "search_queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_text", sa.String(length=500), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_query", sa.String(length=500), nullable=True),
        sa.Column("entity_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("took_ms", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("clicked_result", sa.Boolean(), nullable=False),
        sa.Column("clicked_position", sa.Integer(), nullable=True),
        sa.Column("clicked_entity_id", sa.String(length=255), nullable=True),
        sa.Column("search_syntax", sa.String(length=50), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_queries")),
    )
    op.create_index(
        op.f("ix_search_queries_query_hash"), "search_queries", ["query_hash"], unique=False
    )
    op.create_index(
        op.f("ix_search_queries_query_text"), "search_queries", ["query_text"], unique=False
    )
    op.create_index(op.f("ix_search_queries_user_id"), "search_queries", ["user_id"], unique=False)
    op.create_table(
        "search_suggestion_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prefix", sa.String(length=100), nullable=False),
        sa.Column("suggested_text", sa.String(length=500), nullable=False),
        sa.Column("was_selected", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_suggestion_logs")),
    )
    op.create_index(
        op.f("ix_search_suggestion_logs_prefix"), "search_suggestion_logs", ["prefix"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Unique tag name (e.g., 'work', 'urgent')",
        ),
        sa.Column(
            "color", sa.String(length=7), nullable=True, comment="Hex color code (e.g., '#FF5733')"
        ),
        sa.Column(
            "description",
            sa.String(length=200),
            nullable=True,
            comment="Optional description of the tag's purpose",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name="uq_tags_name"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_table(
        "task_executions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "task_id",
            sa.String(length=255),
            nullable=False,
            comment="Unique task execution ID from Taskiq",
        ),
        sa.Column(
            "task_name",
            sa.String(length=255),
            nullable=False,
            comment="Task function name (e.g., 'backup_database')",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Status: pending, running, success, failure, cancelled",
        ),
        sa.Column(
            "worker_id",
            sa.String(length=255),
            nullable=True,
            comment="Worker that executed/is executing the task",
        ),
        sa.Column(
            "queue_name", sa.String(length=255), nullable=True, comment="Queue the task was sent to"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the task was enqueued",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When execution started",
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When execution finished",
        ),
        sa.Column(
            "duration_ms", sa.Integer(), nullable=True, comment="Execution duration in milliseconds"
        ),
        sa.Column(
            "return_value",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Task return value (JSON serialized)",
        ),
        sa.Column(
            "error_type",
            sa.String(length=255),
            nullable=True,
            comment="Exception class name if failed",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message if failed"),
        sa.Column("error_traceback", sa.Text(), nullable=True, comment="Full traceback if failed"),
        sa.Column(
            "task_args",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Task positional arguments (JSON)",
        ),
        sa.Column(
            "task_kwargs",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Task keyword arguments (JSON)",
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Task labels/metadata for categorization",
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="Number of retry attempts"),
        sa.Column(
            "max_retries", sa.Integer(), nullable=True, comment="Maximum retry attempts configured"
        ),
        sa.Column(
            "progress",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Task progress data for long-running tasks",
        ),
        sa.Column(
            "serialized_result",
            sa.LargeBinary(),
            nullable=True,
            comment="Full serialized TaskiqResult for backend compatibility",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_executions")),
    )
    op.create_index(
        "ix_task_exec_created_desc",
        "task_executions",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_task_exec_name_status", "task_executions", ["task_name", "status"], unique=False
    )
    op.create_index(
        "ix_task_exec_status_created", "task_executions", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_task_exec_worker_status", "task_executions", ["worker_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_task_executions_created_at"), "task_executions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_task_executions_error_type"), "task_executions", ["error_type"], unique=False
    )
    op.create_index(op.f("ix_task_executions_status"), "task_executions", ["status"], unique=False)
    op.create_index(op.f("ix_task_executions_task_id"), "task_executions", ["task_id"], unique=True)
    op.create_index(
        op.f("ix_task_executions_task_name"), "task_executions", ["task_name"], unique=False
    )
    op.create_index(
        op.f("ix_task_executions_worker_id"), "task_executions", ["worker_id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "search_vector",
            TSVECTOR(),
            nullable=True,
            comment="Full-text search vector for email, username, and full_name",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_email_username", "users", ["email", "username"], unique=False)
    op.create_index("ix_users_is_active", "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name", sa.String(length=200), nullable=False, comment="Human-readable webhook name"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Webhook description"),
        sa.Column(
            "url", sa.String(length=2048), nullable=False, comment="Target URL for webhook delivery"
        ),
        sa.Column(
            "secret",
            sa.String(length=255),
            nullable=False,
            comment="HMAC secret for signing payloads",
        ),
        sa.Column(
            "event_types",
            StringArray(),
            nullable=False,
            comment="List of event types this webhook subscribes to",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Whether webhook is active"),
        sa.Column(
            "max_retries", sa.Integer(), nullable=False, comment="Maximum delivery retry attempts"
        ),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=False,
            comment="HTTP request timeout in seconds",
        ),
        sa.Column(
            "custom_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
            comment="Additional HTTP headers to include in requests",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=255),
            nullable=True,
            comment="Tenant ID for multi-tenant isolation",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhooks")),
    )
    op.create_index(op.f("ix_webhooks_tenant_id"), "webhooks", ["tenant_id"], unique=False)
    op.create_table(
        "ai_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "job_type",
            postgresql.ENUM(
                "TRANSCRIPTION",
                "PII_REDACTION",
                "SUMMARY",
                "SENTIMENT",
                "COACHING",
                "FULL_ANALYSIS",
                name="aijobtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="aijobstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "input_data",
            sa.JSON(),
            nullable=False,
            comment="Job input parameters and data references",
        ),
        sa.Column(
            "result_data",
            sa.JSON(),
            nullable=True,
            comment="Processing results (transcripts, summaries, etc.)",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error details if failed"),
        sa.Column(
            "progress_percentage", sa.Integer(), nullable=False, comment="0-100 progress indicator"
        ),
        sa.Column(
            "current_step",
            sa.String(length=255),
            nullable=True,
            comment="Current processing step description",
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="When processing started"),
        sa.Column(
            "completed_at", sa.DateTime(), nullable=True, comment="When processing completed"
        ),
        sa.Column(
            "duration_seconds", sa.Float(), nullable=True, comment="Total processing duration"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_ai_jobs_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_jobs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_jobs")),
    )
    op.create_index("ix_ai_jobs_created_at", "ai_jobs", ["created_at"], unique=False)
    op.create_index("ix_ai_jobs_status_created", "ai_jobs", ["status", "created_at"], unique=False)
    op.create_index("ix_ai_jobs_tenant_status", "ai_jobs", ["tenant_id", "status"], unique=False)
    op.create_index("ix_ai_jobs_tenant_type", "ai_jobs", ["tenant_id", "job_type"], unique=False)
    op.create_table(
        "email_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.String(length=255),
            nullable=True,
            comment="Tenant ID (nullable for system emails)",
        ),
        sa.Column(
            "recipient_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA256 hash of recipient email",
        ),
        sa.Column("template_name", sa.String(length=255), nullable=True, comment="Template used"),
        sa.Column(
            "subject_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA256 hash of subject (for duplicate detection)",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Status: queued, sent, failed, bounced",
        ),
        sa.Column("provider", sa.String(length=50), nullable=True, comment="Provider used"),
        sa.Column(
            "message_id", sa.String(length=255), nullable=True, comment="Provider message ID"
        ),
        sa.Column(
            "error_category",
            sa.String(length=50),
            nullable=True,
            comment="Error category if failed",
        ),
        sa.Column(
            "trace_id", sa.String(length=64), nullable=True, comment="OpenTelemetry trace ID"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_email_audit_logs_tenant_id_tenants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_audit_logs")),
    )
    op.create_index(
        op.f("ix_email_audit_logs_created_at"), "email_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_email_audit_logs_recipient",
        "email_audit_logs",
        ["recipient_hash", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_audit_logs_recipient_hash"),
        "email_audit_logs",
        ["recipient_hash"],
        unique=False,
    )
    op.create_index(
        "ix_email_audit_logs_status", "email_audit_logs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_email_audit_logs_tenant_created",
        "email_audit_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_audit_logs_tenant_id"), "email_audit_logs", ["tenant_id"], unique=False
    )
    op.create_table(
        "email_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider_type",
            postgresql.ENUM(
                "smtp",
                "aws_ses",
                "sendgrid",
                "mailgun",
                "console",
                "file",
                name="emailprovidertype",
                create_type=False,
            ),
            nullable=False,
            comment="Email provider type (smtp, aws_ses, sendgrid, mailgun, console, file)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Whether this config is active"
        ),
        sa.Column(
            "smtp_host", sa.String(length=255), nullable=True, comment="SMTP server hostname"
        ),
        sa.Column(
            "smtp_port",
            sa.Integer(),
            nullable=True,
            comment="SMTP server port (587 for TLS, 465 for SSL)",
        ),
        sa.Column(
            "smtp_username",
            sa.String(length=255),
            nullable=True,
            comment="SMTP authentication username",
        ),
        sa.Column(
            "smtp_password",
            EncryptedString(max_length=500),
            nullable=True,
            comment="SMTP authentication password (encrypted)",
        ),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=True, comment="Use STARTTLS (port 587)"),
        sa.Column(
            "smtp_use_ssl", sa.Boolean(), nullable=True, comment="Use implicit SSL (port 465)"
        ),
        sa.Column(
            "aws_region",
            sa.String(length=50),
            nullable=True,
            comment="AWS region for SES (e.g., us-east-1)",
        ),
        sa.Column(
            "aws_access_key",
            EncryptedString(max_length=500),
            nullable=True,
            comment="AWS access key ID (encrypted)",
        ),
        sa.Column(
            "aws_secret_key",
            EncryptedString(max_length=500),
            nullable=True,
            comment="AWS secret access key (encrypted)",
        ),
        sa.Column(
            "aws_configuration_set",
            sa.String(length=255),
            nullable=True,
            comment="AWS SES configuration set name for tracking",
        ),
        sa.Column(
            "api_key",
            EncryptedString(max_length=500),
            nullable=True,
            comment="API key for SendGrid/Mailgun (encrypted)",
        ),
        sa.Column(
            "api_endpoint",
            sa.String(length=255),
            nullable=True,
            comment="Custom API endpoint (for Mailgun EU, etc.)",
        ),
        sa.Column(
            "from_email",
            sa.String(length=255),
            nullable=True,
            comment="Default sender email address",
        ),
        sa.Column(
            "from_name", sa.String(length=255), nullable=True, comment="Default sender display name"
        ),
        sa.Column(
            "reply_to", sa.String(length=255), nullable=True, comment="Default reply-to address"
        ),
        sa.Column(
            "rate_limit_per_minute",
            sa.Integer(),
            nullable=True,
            comment="Max emails per minute (None = use system default)",
        ),
        sa.Column(
            "rate_limit_per_hour",
            sa.Integer(),
            nullable=True,
            comment="Max emails per hour (None = use system default)",
        ),
        sa.Column(
            "daily_quota",
            sa.Integer(),
            nullable=True,
            comment="Max emails per day (None = unlimited)",
        ),
        sa.Column(
            "cost_per_email_usd",
            sa.Float(),
            nullable=True,
            comment="Cost per email in USD for billing calculation",
        ),
        sa.Column(
            "monthly_budget_usd",
            sa.Float(),
            nullable=True,
            comment="Monthly email spending limit in USD",
        ),
        sa.Column(
            "config_json",
            sa.JSON(),
            nullable=True,
            comment="Additional provider-specific configuration",
        ),
        sa.Column(
            "encryption_version",
            sa.Integer(),
            nullable=False,
            comment="Encryption key version for rotation",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_email_configs_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_email_configs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_configs")),
    )
    op.create_index("ix_email_configs_provider", "email_configs", ["provider_type"], unique=False)
    op.create_index(
        "ix_email_configs_tenant_active", "email_configs", ["tenant_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_email_configs_tenant_id"), "email_configs", ["tenant_id"], unique=True)
    op.create_table(
        "email_usage_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="Provider used (smtp, sendgrid, etc.)",
        ),
        sa.Column("recipients_count", sa.Integer(), nullable=False, comment="Number of recipients"),
        sa.Column("cost_usd", sa.Float(), nullable=True, comment="Calculated cost in USD"),
        sa.Column("success", sa.Boolean(), nullable=False, comment="Whether delivery succeeded"),
        sa.Column(
            "duration_ms", sa.Integer(), nullable=True, comment="Delivery duration in milliseconds"
        ),
        sa.Column(
            "message_id",
            sa.String(length=255),
            nullable=True,
            comment="Provider message ID for tracking",
        ),
        sa.Column(
            "error_category",
            sa.String(length=50),
            nullable=True,
            comment="Error category if failed (auth, network, recipient, quota)",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error details if failed"),
        sa.Column(
            "trace_id",
            sa.String(length=64),
            nullable=True,
            comment="OpenTelemetry trace ID for correlation",
        ),
        sa.Column(
            "template_name", sa.String(length=255), nullable=True, comment="Template used (if any)"
        ),
        sa.Column(
            "metadata_json", sa.JSON(), nullable=True, comment="Additional operation metadata"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_email_usage_logs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_usage_logs")),
    )
    op.create_index(
        "ix_email_usage_logs_created_at", "email_usage_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_email_usage_logs_tenant_created",
        "email_usage_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_usage_logs_tenant_id"), "email_usage_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_email_usage_logs_tenant_provider",
        "email_usage_logs",
        ["tenant_id", "provider"],
        unique=False,
    )
    op.create_table(
        "file_thumbnails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_file_thumbnails_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_thumbnails")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_file_thumbnails_storage_key")),
    )
    op.create_index(
        op.f("ix_file_thumbnails_file_id"), "file_thumbnails", ["file_id"], unique=False
    )
    op.create_table(
        "job_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "RETRYING",
                "PAUSED",
                name="jobstatus",
                create_type=False,
            ),
            nullable=True,
            comment="Previous status (None for creation)",
        ),
        sa.Column(
            "to_status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "RETRYING",
                "PAUSED",
                name="jobstatus",
                create_type=False,
            ),
            nullable=False,
            comment="New status",
        ),
        sa.Column(
            "triggered_by",
            sa.String(length=100),
            nullable=False,
            comment="What triggered the transition: user, system, timeout, dependency",
        ),
        sa.Column(
            "actor_id", sa.String(length=255), nullable=True, comment="User ID if user-triggered"
        ),
        sa.Column(
            "reason", sa.Text(), nullable=True, comment="Human-readable reason for transition"
        ),
        sa.Column(
            "extra_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional context data",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_audit_logs_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_audit_logs")),
    )
    op.create_index(
        "ix_job_audit_job_created", "job_audit_logs", ["job_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_audit_logs_created_at"), "job_audit_logs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_job_audit_logs_job_id"), "job_audit_logs", ["job_id"], unique=False)
    op.create_table(
        "job_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "required",
            sa.Boolean(),
            nullable=False,
            comment="True = hard dependency (blocks), False = soft (ordering hint)",
        ),
        sa.Column(
            "satisfied", sa.Boolean(), nullable=False, comment="Whether dependency is satisfied"
        ),
        sa.Column(
            "satisfied_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When dependency was satisfied",
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_job_id"],
            ["jobs.id"],
            name=op.f("fk_job_dependencies_depends_on_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_dependencies_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_dependencies")),
        sa.UniqueConstraint("job_id", "depends_on_job_id", name="uq_job_dependency"),
    )
    op.create_index(
        op.f("ix_job_dependencies_depends_on_job_id"),
        "job_dependencies",
        ["depends_on_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_dependencies_job_id"), "job_dependencies", ["job_id"], unique=False
    )
    op.create_index(
        "ix_job_deps_unsatisfied",
        "job_dependencies",
        ["job_id"],
        unique=False,
        postgresql_where=sa.text("NOT satisfied"),
    )
    op.create_table(
        "job_labels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False, comment="Label key"),
        sa.Column("value", sa.String(length=255), nullable=False, comment="Label value"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_labels_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_labels")),
        sa.UniqueConstraint("job_id", "key", name="uq_job_label_key"),
    )
    op.create_index(op.f("ix_job_labels_job_id"), "job_labels", ["job_id"], unique=False)
    op.create_index("ix_job_labels_key_value", "job_labels", ["key", "value"], unique=False)
    op.create_table(
        "job_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("percentage", sa.Integer(), nullable=False, comment="0-100 percentage complete"),
        sa.Column(
            "current_stage", sa.String(length=255), nullable=True, comment="Current stage name"
        ),
        sa.Column("total_stages", sa.Integer(), nullable=False, comment="Total number of stages"),
        sa.Column(
            "completed_stages", sa.Integer(), nullable=False, comment="Completed stages count"
        ),
        sa.Column(
            "current_item", sa.Integer(), nullable=False, comment="Current item being processed"
        ),
        sa.Column("total_items", sa.Integer(), nullable=False, comment="Total items to process"),
        sa.Column(
            "estimated_completion",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Estimated completion time",
        ),
        sa.Column(
            "message", sa.Text(), nullable=True, comment="Custom progress message for display"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_progress_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_progress")),
        sa.UniqueConstraint("job_id", name=op.f("uq_job_progress_job_id")),
    )
    op.create_table(
        "job_webhooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False, comment="Webhook endpoint URL"),
        sa.Column(
            "secret",
            sa.String(length=255),
            nullable=True,
            comment="HMAC secret for signature verification",
        ),
        sa.Column(
            "on_completed", sa.Boolean(), nullable=False, comment="Fire on successful completion"
        ),
        sa.Column("on_failed", sa.Boolean(), nullable=False, comment="Fire on failure"),
        sa.Column("on_cancelled", sa.Boolean(), nullable=False, comment="Fire on cancellation"),
        sa.Column(
            "on_progress",
            sa.Boolean(),
            nullable=False,
            comment="Fire on progress updates (debounced)",
        ),
        sa.Column(
            "last_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last delivery attempt",
        ),
        sa.Column(
            "last_success_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last successful delivery",
        ),
        sa.Column("failure_count", sa.Integer(), nullable=False, comment="Consecutive failures"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_webhooks_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_webhooks")),
    )
    op.create_index(op.f("ix_job_webhooks_job_id"), "job_webhooks", ["job_id"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "search_vector",
            TSVECTOR(),
            nullable=True,
            comment="Full-text search vector for title, content, and slug",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_posts_author_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("slug", name=op.f("uq_posts_slug")),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index(
        "ix_posts_author_id_is_published", "posts", ["author_id", "is_published"], unique=False
    )
    op.create_index("ix_posts_slug", "posts", ["slug"], unique=False)
    op.create_table(
        "reminder_tags",
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_reminder_tags_reminder_id_reminders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_reminder_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("reminder_id", "tag_id", name=op.f("pk_reminder_tags")),
    )
    op.create_table(
        "tenant_ai_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider_type",
            postgresql.ENUM(
                "LLM",
                "TRANSCRIPTION",
                "EMBEDDING",
                "IMAGE",
                "PII_REDACTION",
                name="aiprovidertype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider_name",
            sa.String(length=100),
            nullable=False,
            comment="openai|anthropic|deepgram|etc",
        ),
        sa.Column(
            "model_name",
            sa.String(length=255),
            nullable=True,
            comment="Optional model override (e.g., gpt-4, claude-3)",
        ),
        sa.Column(
            "encrypted_api_key", sa.Text(), nullable=True, comment="Encrypted API key for provider"
        ),
        sa.Column(
            "config_json",
            sa.JSON(),
            nullable=True,
            comment="Additional provider-specific configuration",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tenant_ai_configs_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_ai_configs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_ai_configs")),
    )
    op.create_index(
        "ix_tenant_ai_configs_tenant_active",
        "tenant_ai_configs",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_tenant_ai_configs_tenant_provider",
        "tenant_ai_configs",
        ["tenant_id", "provider_type", "provider_name"],
        unique=False,
    )
    op.create_table(
        "tenant_ai_features",
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("transcription_enabled", sa.Boolean(), nullable=False),
        sa.Column("pii_redaction_enabled", sa.Boolean(), nullable=False),
        sa.Column("summary_enabled", sa.Boolean(), nullable=False),
        sa.Column("sentiment_enabled", sa.Boolean(), nullable=False),
        sa.Column("coaching_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "pii_entity_types",
            sa.JSON(),
            nullable=True,
            comment="List of PII entity types to detect/redact",
        ),
        sa.Column(
            "pii_confidence_threshold",
            sa.Float(),
            nullable=True,
            comment="Minimum confidence for PII detection (0.0-1.0)",
        ),
        sa.Column(
            "max_audio_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Maximum audio duration for transcription (override global)",
        ),
        sa.Column(
            "max_concurrent_jobs",
            sa.Integer(),
            nullable=True,
            comment="Maximum concurrent AI jobs (override global)",
        ),
        sa.Column(
            "monthly_budget_usd",
            sa.Float(),
            nullable=True,
            comment="Monthly AI spending limit in USD",
        ),
        sa.Column(
            "enable_cost_alerts", sa.Boolean(), nullable=False, comment="Send alerts on high costs"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_ai_features_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenant_ai_features")),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "webhook_id", sa.Uuid(), nullable=False, comment="Reference to webhook configuration"
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Type of event being delivered",
        ),
        sa.Column(
            "event_id",
            sa.String(length=255),
            nullable=False,
            comment="Unique identifier for the event",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
            comment="Event payload data",
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "delivered",
                "failed",
                "retrying",
                name="deliverystatus",
                create_type=False,
            ),
            nullable=False,
            comment="Delivery status: pending, delivered, failed, retrying",
        ),
        sa.Column(
            "attempt_count",
            sa.Integer(),
            nullable=False,
            comment="Number of delivery attempts made",
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=False, comment="Maximum attempts allowed"),
        sa.Column(
            "next_retry_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Scheduled time for next retry attempt",
        ),
        sa.Column(
            "response_status_code", sa.Integer(), nullable=True, comment="HTTP response status code"
        ),
        sa.Column(
            "response_body", sa.Text(), nullable=True, comment="HTTP response body (truncated)"
        ),
        sa.Column(
            "response_time_ms", sa.Integer(), nullable=True, comment="Response time in milliseconds"
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error message if delivery failed"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of record creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
            name=op.f("fk_webhook_deliveries_webhook_id_webhooks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_id"), "webhook_deliveries", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_type"), "webhook_deliveries", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_next_retry_at"),
        "webhook_deliveries",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_status"), "webhook_deliveries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False
    )
    op.create_table(
        "ai_usage_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True, comment="Associated AI job"),
        sa.Column(
            "provider_name",
            sa.String(length=100),
            nullable=False,
            comment="openai|anthropic|deepgram|etc",
        ),
        sa.Column(
            "model_name",
            sa.String(length=255),
            nullable=False,
            comment="Specific model used (gpt-4, nova-2, etc)",
        ),
        sa.Column(
            "operation_type",
            sa.String(length=100),
            nullable=False,
            comment="transcription|llm_generation|embedding|pii_detection",
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True, comment="Input tokens (LLM)"),
        sa.Column("output_tokens", sa.Integer(), nullable=True, comment="Output tokens (LLM)"),
        sa.Column(
            "audio_seconds", sa.Float(), nullable=True, comment="Audio duration (transcription)"
        ),
        sa.Column(
            "characters_processed",
            sa.Integer(),
            nullable=True,
            comment="Characters processed (PII, etc.)",
        ),
        sa.Column("cost_usd", sa.Float(), nullable=False, comment="Calculated cost in USD"),
        sa.Column(
            "cost_calculation_method",
            sa.String(length=50),
            nullable=True,
            comment="How cost was calculated (api_reported|estimated)",
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=False, comment="Operation duration"),
        sa.Column("success", sa.Boolean(), nullable=False, comment="Whether operation succeeded"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error if failed"),
        sa.Column(
            "metadata_json",
            sa.JSON(),
            nullable=True,
            comment="Additional operation-specific metadata",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ai_jobs.id"],
            name=op.f("fk_ai_usage_logs_job_id_ai_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_usage_logs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_logs")),
    )
    op.create_index("ix_ai_usage_logs_created_at", "ai_usage_logs", ["created_at"], unique=False)
    op.create_index("ix_ai_usage_logs_job", "ai_usage_logs", ["job_id"], unique=False)
    op.create_index(
        "ix_ai_usage_logs_tenant_created",
        "ai_usage_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_usage_logs_tenant_provider",
        "ai_usage_logs",
        ["tenant_id", "provider_name"],
        unique=False,
    )

    # Create required PostgreSQL extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")

    # Add Full-Text Search triggers for automatic search_vector updates
    # Users FTS
    helper_users = FTSMigrationHelper(
        table_name="users",
        search_fields=["email", "username", "full_name"],
        weights={"email": "A", "username": "A", "full_name": "B"},
        config="simple",
    )

    # Create GIN index (column already exists from table creation)
    op.create_index(
        helper_users.index_name,
        "users",
        [helper_users.column_name],
        unique=False,
        postgresql_using="gin",
    )

    # Create trigger function and trigger
    op.execute(helper_users.get_trigger_function_sql())
    op.execute(helper_users.get_trigger_sql())

    # Backfill existing data (usually empty for initial migration)
    op.execute(helper_users.get_backfill_sql())

    # Posts FTS
    helper_posts = FTSMigrationHelper(
        table_name="posts",
        search_fields=["title", "content", "slug"],
        weights={"title": "A", "content": "B", "slug": "C"},
        config="english",
    )

    # Create GIN index (column already exists from table creation)
    op.create_index(
        helper_posts.index_name,
        "posts",
        [helper_posts.column_name],
        unique=False,
        postgresql_using="gin",
    )

    # Create trigger function and trigger
    op.execute(helper_posts.get_trigger_function_sql())
    op.execute(helper_posts.get_trigger_sql())

    # Backfill existing data (usually empty for initial migration)
    op.execute(helper_posts.get_backfill_sql())

    # Reminders FTS
    helper_reminders = FTSMigrationHelper(
        table_name="reminders",
        search_fields=["title", "description"],
        config="english",
    )

    # Create GIN index (column already exists from table creation)
    op.create_index(
        helper_reminders.index_name,
        "reminders",
        [helper_reminders.column_name],
        unique=False,
        postgresql_using="gin",
    )

    # Create trigger function and trigger
    op.execute(helper_reminders.get_trigger_function_sql())
    op.execute(helper_reminders.get_trigger_sql())

    # Backfill existing data (usually empty for initial migration)
    op.execute(helper_reminders.get_backfill_sql())

    # Create trigram indexes for fuzzy search
    # users.username trigram index
    op.create_index(
        "ix_users_username_trgm",
        "users",
        ["username"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={"username": "gist_trgm_ops"},
    )

    # users.full_name trigram index
    op.create_index(
        "ix_users_full_name_trgm",
        "users",
        ["full_name"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={"full_name": "gist_trgm_ops"},
    )

    # posts.title trigram index
    op.create_index(
        "ix_posts_title_trgm",
        "posts",
        ["title"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={"title": "gist_trgm_ops"},
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove trigram indexes
    op.drop_index("ix_posts_title_trgm", table_name="posts")
    op.drop_index("ix_users_full_name_trgm", table_name="users")
    op.drop_index("ix_users_username_trgm", table_name="users")

    # Remove Full-Text Search triggers
    FTSMigrationHelper(
        table_name="reminders",
        search_fields=["title", "description"],
        config="english",
    ).remove_fts(op)  # type: ignore[arg-type]

    FTSMigrationHelper(
        table_name="posts",
        search_fields=["title", "content", "slug"],
        weights={"title": "A", "content": "B", "slug": "C"},
        config="english",
    ).remove_fts(op)  # type: ignore[arg-type]

    FTSMigrationHelper(
        table_name="users",
        search_fields=["email", "username", "full_name"],
        weights={"email": "A", "username": "A", "full_name": "B"},
        config="simple",
    ).remove_fts(op)  # type: ignore[arg-type]

    op.drop_index("ix_ai_usage_logs_tenant_provider", table_name="ai_usage_logs")
    op.drop_index("ix_ai_usage_logs_tenant_created", table_name="ai_usage_logs")
    op.drop_index("ix_ai_usage_logs_job", table_name="ai_usage_logs")
    op.drop_index("ix_ai_usage_logs_created_at", table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_status"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_next_retry_at"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_table("tenant_ai_features")
    op.drop_index("ix_tenant_ai_configs_tenant_provider", table_name="tenant_ai_configs")
    op.drop_index("ix_tenant_ai_configs_tenant_active", table_name="tenant_ai_configs")
    op.drop_table("tenant_ai_configs")
    op.drop_table("reminder_tags")
    op.drop_index("ix_posts_slug", table_name="posts")
    op.drop_index("ix_posts_author_id_is_published", table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_job_webhooks_job_id"), table_name="job_webhooks")
    op.drop_table("job_webhooks")
    op.drop_table("job_progress")
    op.drop_index("ix_job_labels_key_value", table_name="job_labels")
    op.drop_index(op.f("ix_job_labels_job_id"), table_name="job_labels")
    op.drop_table("job_labels")
    op.drop_index(
        "ix_job_deps_unsatisfied",
        table_name="job_dependencies",
        postgresql_where=sa.text("NOT satisfied"),
    )
    op.drop_index(op.f("ix_job_dependencies_job_id"), table_name="job_dependencies")
    op.drop_index(op.f("ix_job_dependencies_depends_on_job_id"), table_name="job_dependencies")
    op.drop_table("job_dependencies")
    op.drop_index(op.f("ix_job_audit_logs_job_id"), table_name="job_audit_logs")
    op.drop_index(op.f("ix_job_audit_logs_created_at"), table_name="job_audit_logs")
    op.drop_index("ix_job_audit_job_created", table_name="job_audit_logs")
    op.drop_table("job_audit_logs")
    op.drop_index(op.f("ix_file_thumbnails_file_id"), table_name="file_thumbnails")
    op.drop_table("file_thumbnails")
    op.drop_index("ix_email_usage_logs_tenant_provider", table_name="email_usage_logs")
    op.drop_index(op.f("ix_email_usage_logs_tenant_id"), table_name="email_usage_logs")
    op.drop_index("ix_email_usage_logs_tenant_created", table_name="email_usage_logs")
    op.drop_index("ix_email_usage_logs_created_at", table_name="email_usage_logs")
    op.drop_table("email_usage_logs")
    op.drop_index(op.f("ix_email_configs_tenant_id"), table_name="email_configs")
    op.drop_index("ix_email_configs_tenant_active", table_name="email_configs")
    op.drop_index("ix_email_configs_provider", table_name="email_configs")
    op.drop_table("email_configs")
    op.drop_index(op.f("ix_email_audit_logs_tenant_id"), table_name="email_audit_logs")
    op.drop_index("ix_email_audit_logs_tenant_created", table_name="email_audit_logs")
    op.drop_index("ix_email_audit_logs_status", table_name="email_audit_logs")
    op.drop_index(op.f("ix_email_audit_logs_recipient_hash"), table_name="email_audit_logs")
    op.drop_index("ix_email_audit_logs_recipient", table_name="email_audit_logs")
    op.drop_index(op.f("ix_email_audit_logs_created_at"), table_name="email_audit_logs")
    op.drop_table("email_audit_logs")
    op.drop_index("ix_ai_jobs_tenant_type", table_name="ai_jobs")
    op.drop_index("ix_ai_jobs_tenant_status", table_name="ai_jobs")
    op.drop_index("ix_ai_jobs_status_created", table_name="ai_jobs")
    op.drop_index("ix_ai_jobs_created_at", table_name="ai_jobs")
    op.drop_table("ai_jobs")
    op.drop_index(op.f("ix_webhooks_tenant_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_index("ix_users_email_username", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_task_executions_worker_id"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_task_name"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_task_id"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_status"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_error_type"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_created_at"), table_name="task_executions")
    op.drop_index("ix_task_exec_worker_status", table_name="task_executions")
    op.drop_index("ix_task_exec_status_created", table_name="task_executions")
    op.drop_index("ix_task_exec_name_status", table_name="task_executions")
    op.drop_index(
        "ix_task_exec_created_desc", table_name="task_executions", postgresql_using="btree"
    )
    op.drop_table("task_executions")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_search_suggestion_logs_prefix"), table_name="search_suggestion_logs")
    op.drop_table("search_suggestion_logs")
    op.drop_index(op.f("ix_search_queries_user_id"), table_name="search_queries")
    op.drop_index(op.f("ix_search_queries_query_text"), table_name="search_queries")
    op.drop_index(op.f("ix_search_queries_query_hash"), table_name="search_queries")
    op.drop_table("search_queries")
    op.drop_index(op.f("ix_reminders_tenant_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_parent_id"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index("ix_jobs_tenant_status", table_name="jobs")
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index("ix_jobs_task_name_status", table_name="jobs")
    op.drop_index(op.f("ix_jobs_task_name"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(
        "ix_jobs_running_timeout",
        table_name="jobs",
        postgresql_where=sa.text("status = 'running' AND timeout_seconds IS NOT NULL"),
    )
    op.drop_index(
        "ix_jobs_priority_queued", table_name="jobs", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_index(op.f("ix_jobs_parent_job_id"), table_name="jobs")
    op.drop_index(
        "ix_jobs_completed_cleanup",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"),
    )
    op.drop_table("jobs")
    op.drop_index("ix_flag_overrides_lookup", table_name="flag_overrides")
    op.drop_index(op.f("ix_flag_overrides_flag_key"), table_name="flag_overrides")
    op.drop_index("ix_flag_overrides_entity", table_name="flag_overrides")
    op.drop_table("flag_overrides")
    op.drop_index(op.f("ix_files_tenant_id"), table_name="files")
    op.drop_index(op.f("ix_files_storage_key"), table_name="files")
    op.drop_index(op.f("ix_files_status"), table_name="files")
    op.drop_index(op.f("ix_files_owner_id"), table_name="files")
    op.drop_table("files")
    op.drop_index("ix_feature_flags_status", table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
    op.drop_index("ix_feature_flags_enabled", table_name="feature_flags")
    op.drop_table("feature_flags")
    op.drop_index("ix_audit_user_time", table_name="audit_logs")
    op.drop_index("ix_audit_tenant_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_index("ix_audit_action_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    sa.Enum(
        "smtp", "aws_ses", "sendgrid", "mailgun", "console", "file", name="emailprovidertype"
    ).drop(op.get_bind())
    sa.Enum("pending", "delivered", "failed", "retrying", name="deliverystatus").drop(op.get_bind())
    sa.Enum("pending", "processing", "ready", "failed", "deleted", name="filestatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "create",
        "read",
        "update",
        "delete",
        "bulk_create",
        "bulk_update",
        "bulk_delete",
        "export",
        "import",
        "login",
        "logout",
        "login_failed",
        "password_change",
        "token_refresh",
        "permission_denied",
        "acl_check",
        "archive",
        "restore",
        "purge",
        name="auditaction",
    ).drop(op.get_bind())
    sa.Enum("enabled", "disabled", "percentage", "targeted", name="flagstatus").drop(op.get_bind())
    sa.Enum(
        "LLM", "TRANSCRIPTION", "EMBEDDING", "IMAGE", "PII_REDACTION", name="aiprovidertype"
    ).drop(op.get_bind())
    sa.Enum(
        "TRANSCRIPTION",
        "PII_REDACTION",
        "SUMMARY",
        "SENTIMENT",
        "COACHING",
        "FULL_ANALYSIS",
        name="aijobtype",
    ).drop(op.get_bind())
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", name="aijobstatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "pending",
        "queued",
        "running",
        "completed",
        "failed",
        "cancelled",
        "retrying",
        "paused",
        name="jobstatus",
    ).drop(op.get_bind())
    sa.Enum("1", "2", "3", "4", name="jobpriority").drop(op.get_bind())
    # ### end Alembic commands ###
